repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
      - id: check-yaml
  - repo: local
    hooks:
    -   id: isort
        name: isort
        entry: pipenv run isort -rc .
        'types': [python]
        language: system
    -   id: black
        name: black
        language: system
        entry: pipenv run black .
        'types': [python]
    -   id: flake8
        name: flake8
        entry: pipenv run flake8 .
        'types': [python]
        language: system
    -   id: mypy
        name: mypy
        require_serial: true
        entry: pipenv run mypy
        'types': [python]
        language: system
    -   id: pytest
        name: pytest
        entry: pipenv run pytest
        'types': [python]
        language: system
